# Site settings
title: Presentation Page
email: walter@stormsavvy.com
description: "Presentation Page for Storm Savvy"
baseurl: ""
url: "http://stormsavvy.co"
twitter_username: stormsavvy
github_username:  stormsavvy

# Build settings
markdown: kramdown
permalink: pretty
