git rm    kharma/.gitignore
git rm    kharma/_config.yml
git rm    kharma/_includes/footer.html
git rm    kharma/_includes/head.html
git rm    kharma/_includes/header.html
git rm    kharma/_layouts/default.html
git rm    kharma/_layouts/page.html
git rm    kharma/_layouts/post.html
git rm    kharma/_posts/2014-11-20-east-bay-rails-meetup.markdown
git rm    kharma/about.md
git rm    kharma/css/main.css
git rm    kharma/ebr_files/noaa_forecast_service.rb
git rm    kharma/ebr_files/noaa_forecast_service_spec.rb
git rm    kharma/feed.xml
git rm    kharma/index.html
